version: '3.8'
services:
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
        - '6000:27017'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  backend:
    build: ../backend
    ports:
      - '8000:8000'
    env_file:
      - ../backend/.env
    volumes:
      - logs:/app/backend/logs
      - ../backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongo
      - redis

  frontend:
    build: ../frontend
    ports:
      - '5173:5173'
    env_file:
    - ../frontend/.env
    volumes: 
    - ../frontend:/app/frontend
    - /app/frontend/node_modules
    depends_on:
    - backend

volumes:
  mongo:
  redis:
  logs: